-- SideFit 추천 임베딩 저장소 확장
-- Supabase SQL Editor에서 한 번 실행한다.

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

SET search_path TO sidefit, extensions, public;

CREATE TABLE IF NOT EXISTS user_embeddings (
    user_embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    normalized_text TEXT NOT NULL,
    embedding extensions.vector(768) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    embedding_version VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_embeddings PRIMARY KEY (user_embedding_id),
    CONSTRAINT uk_user_embeddings_version UNIQUE (user_id, embedding_version),
    CONSTRAINT fk_user_embeddings_users FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_embeddings (
    project_embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT NOT NULL,
    normalized_text TEXT NOT NULL,
    embedding extensions.vector(768) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    embedding_version VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_project_embeddings PRIMARY KEY (project_embedding_id),
    CONSTRAINT uk_project_embeddings_version UNIQUE (project_id, embedding_version),
    CONSTRAINT fk_project_embeddings_projects FOREIGN KEY (project_id)
        REFERENCES projects (project_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_embeddings_cosine
    ON user_embeddings USING hnsw (embedding extensions.vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_project_embeddings_cosine
    ON project_embeddings USING hnsw (embedding extensions.vector_cosine_ops);

COMMENT ON TABLE user_embeddings IS '사용자 추천 임베딩';
COMMENT ON COLUMN user_embeddings.user_embedding_id IS '사용자 임베딩 식별자';
COMMENT ON COLUMN user_embeddings.user_id IS '회원 식별자';
COMMENT ON COLUMN user_embeddings.normalized_text IS '임베딩 생성에 사용한 정규화 텍스트';
COMMENT ON COLUMN user_embeddings.embedding IS 'Gemini 768차원 임베딩';
COMMENT ON COLUMN user_embeddings.embedding_model IS '임베딩 모델명';
COMMENT ON COLUMN user_embeddings.embedding_version IS '임베딩 처리 버전';
COMMENT ON COLUMN user_embeddings.content_hash IS '정규화 텍스트 SHA-256 해시';
COMMENT ON COLUMN user_embeddings.created_at IS '생성 일시';
COMMENT ON COLUMN user_embeddings.updated_at IS '수정 일시';

COMMENT ON TABLE project_embeddings IS '프로젝트 추천 임베딩';
COMMENT ON COLUMN project_embeddings.project_embedding_id IS '프로젝트 임베딩 식별자';
COMMENT ON COLUMN project_embeddings.project_id IS '프로젝트 식별자';
COMMENT ON COLUMN project_embeddings.normalized_text IS '임베딩 생성에 사용한 정규화 텍스트';
COMMENT ON COLUMN project_embeddings.embedding IS 'Gemini 768차원 임베딩';
COMMENT ON COLUMN project_embeddings.embedding_model IS '임베딩 모델명';
COMMENT ON COLUMN project_embeddings.embedding_version IS '임베딩 처리 버전';
COMMENT ON COLUMN project_embeddings.content_hash IS '정규화 텍스트 SHA-256 해시';
COMMENT ON COLUMN project_embeddings.created_at IS '생성 일시';
COMMENT ON COLUMN project_embeddings.updated_at IS '수정 일시';
